version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@prisma/client"
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.1
    - 2.21.0
    - 2.21.1
  - dependency-name: "@prisma/cli"
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.0-dev.43
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
